### ISSUE TITLE
double CAMES for wildcard domains?

### ISSUE THREAD

**Issue by dirtbag** [joohoi/acme-dns-certbot#9] opened 2018-06-15 21:04 UTC
when I try to get a wildcard cert for my    mydomain.com and *.mydomain.com, the certbot comes back with asking me to add 2 CNAMES with the same name to different hosts. Ive searched and this doesn't seem to be a valid DNS option.

Output from acme-dns-auth.py:
Please add the following CNAME record to your main DNS zone:
_acme-challenge.mydomain.com CNAME 34b62d67-4a60-4cc5-a30e-ceddf6f61cf0.auth.mydomain.com.

Output from acme-dns-auth.py:
Please add the following CNAME record to your main DNS zone:
_acme-challenge.mydomain.com CNAME 7879f9a9-1fd4-44a0-bc76-048390ffec62.auth.mydomain.com.

This doesnt seem right, am I really supposed to put 2 CNAMES in like this?

-db

**Comment by joohoi** [comment] 2018-06-15 21:17
This certainly isn't possible to do in DNS, and looks like a bug in the authentication hook code. I'll investigate a bit. Thanks for opening the issue!

**Comment by joohoi** [comment] 2018-06-15 21:21
After a quick look, this should be handled by the authentication hook, here:

https://github.com/joohoi/acme-dns-certbot-joohoi/blob/master/acme-dns-auth.py#L120-L126

I'm a bit lost why it doesn't work for you. Can you double check the `-d` arguments you're passing to Certbot?

**Comment by dirtbag** [comment] 2018-06-15 21:29
i just looked at my acme-dns-auth.py and at that block of code, I have that code..  at line 120: 

    def put(self, key, value):
        """Puts the configuration value to storage and sanitize it"""
        # If wildcard domain, remove the wildcard part as this will use the
        # same validation record name as the base domain
        if key.startswith("*."):
            key = key[2:]
        self._data[key] = value
 
what else can I do to help troubleshoot/debug this?

-db

**Comment by joohoi** [comment] 2018-06-15 21:32
Can you add these lines before `if key.startswith("*."):`
```
import binascii
print(binascii.hexlify(key))
```

This will convert the key, which is the domain in question to a hex string and print it out. Please note that this output will disclose your domains.

I assume that there's something in the key string itself that makes it not hit the if clause below.

**Comment by dirtbag** [comment] 2018-06-15 21:33
certbot certonly  --server https://acme-v02.api.letsencrypt.org/directory --manual --manual-auth-hook /etc/acme-dns/acme-dns-auth.py --preferred-challenges dns --debug-challenges -d mydomain.com -d *.mydomain.com

is how im running it.. ill add those likes in my code and let you know in a few..

**Comment by joohoi** [comment] 2018-06-15 21:34
Oh! Try to escape the wildcard, as shell might mess it up if you don't. That is `... -d \*.mydomain.com`

**Comment by dirtbag** [comment] 2018-06-15 21:35
actually I tried it with the \*.mydomain.com as well..  I thought that would be the issue as well, but it doesnt seem to help.

**Comment by dirtbag** [comment] 2018-06-15 21:38
now I get ...

(Y)es/(N)o: Y
Output from acme-dns-auth.py:
676c617373747265652e636f6d
Please add the following CNAME record to your main DNS zone:
_acme-challenge.mydomain.com CNAME 00abf720-8b26-4a5f-8e33-97054ada6374.auth.mydomain.com.

Output from acme-dns-auth.py:
676c617373747265652e636f6d
Please add the following CNAME record to your main DNS zone:
_acme-challenge.mydomain.com CNAME 9f1ed737-dcc8-4c1c-9d55-06f177a5889a.auth.mydomain.com.

for the output above,  i tried it with the -d \*.mydomain.com  

-db

**Comment by joohoi** [comment] 2018-06-15 21:43
One thing that comes to mind, is that there might be a problem writing to the account data file: https://github.com/joohoi/acme-dns-certbot-joohoi/blob/master/acme-dns-auth.py#L12 (default value: `/etc/letsencrypt/acmedns.json`). Can you check if the file exists, and if it holds more than one key?

**Comment by joohoi** [comment] 2018-06-15 21:46
Oh! Or do you have `FORCE_REGISTER = True`, as I see a potential bug in handling that!

**Comment by dirtbag** [comment] 2018-06-15 21:47
FORCE_REGISTER = True  where?

**Comment by joohoi** [comment] 2018-06-15 21:47
https://github.com/joohoi/acme-dns-certbot-joohoi/blob/master/acme-dns-auth.py#L17

**Comment by dirtbag** [comment] 2018-06-15 21:48
I do!
```
# Force re-registration. Overwrites the already existing acme-dns accounts.
FORCE_REGISTER = True
```

**Comment by joohoi** [comment] 2018-06-15 21:54
Oh, that's the issue then! It practically registers a new account on each run (and hence prompts the user to update the records). I suggest you change it to `False` and Certbot should prompt you to add only one `CNAME` record and you're good to go!

**Comment by joohoi** [comment] 2018-06-15 21:57
I take that back, you won't be prompted for a `CNAME` addition as the hook finds an already existing account. I suggest you delete the storage file: `/etc/letsencrypt/acmedns.json`, change `FORCE_REGISTER` to `False` and rerun Certbot.

**Comment by joohoi** [comment] 2018-06-15 23:36
I expect that fixed your issue, so I'm going to close this now. If the issue is not resolved, feel free to comment here and I'll reopen.

**Closed as completed by joohoi** 2018-06-15 23:36 UTC
Labels: bug

**Comment by dirtbag** [comment] 2018-06-16 00:53
yaaaa!! that worked!! thanks bro!

-db
